mysite/img/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^newlogo.png', views.index, name='index'),
]

mysite/mainApp/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^100/', views.id1, name='id1'),
    url(r'^100-150/', views.id2, name='id2'),
    url(r'^150/', views.id3, name='id3'),
    url(r'^$', views.index, name='index'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^sip/', include('sip.urls')),
    url(r'^', include('mainApp.urls')),
    url(r'^', include('products.urls')),
    url(r'^$', include('orders.urls')),

] \
                + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
                + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/products/urls.py
from django.conf.urls import url, include
from products import views

urlpatterns = [
    # url(r'^landing123/', views.landing, name='landing'),
    url(r'^product/(?P<product_id>\w+)/$', views.product, name='product'),
]

mysite/mainApp/models.py
from django.db import models

class Subscriber(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=256)

    def __str__(self):
        return "%s) Пользователь  %s" % (self.id, self.name)

    class Meta:
        verbose_name = 'Mysubscriber'
        verbose_name_plural = 'A lot of Subscribers'

mysite/products/models.py
from django.db import models

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" %  self.name

    class Meta:
        verbose_name = 'Категория товара'
        verbose_name_plural = 'Категории товаров'


class Product(models.Model):
    # floors = models.DecimalField(max_digits=1, decimal_places=1, default=1)
    name = models.CharField(max_length=64, blank=True, null=True, default=None)
    category = models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    area = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    floors = models.DecimalField(max_digits=4, decimal_places=0, default=0)
    rooms = models.DecimalField(max_digits=2, decimal_places=0, default=1)
    height = models.DecimalField(max_digits=4, decimal_places=2, default=2.8)
    foundation = models.CharField(max_length=5, blank=True, null=True, default='СВФ')
    price = models.DecimalField(max_digits=10, decimal_places=0, default=0)
    roof_price = models.DecimalField(max_digits=10, decimal_places=0, default=0)
    water_price = models.DecimalField(max_digits=10, decimal_places=0, default=0)
    front_price = models.DecimalField(max_digits=10, decimal_places=0, default=0)
    description = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class ProductImage(models.Model):
    product = models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images/')
    is_main = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'

mysite/mainApp/forms.py
from django import forms
from .models import *

class SubscribersForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        exclude = [""]

mysite/products/forms.py
from django import forms
from .models import *


# class SubscriberForm(forms.ModelForm):
#
#     class Meta:
#         model = Subscriber
#         exclude = [""]

mysite/mainApp/views.py
from django.shortcuts import render
from .forms import SubscribersForm
from products.models import *


def index(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    form = SubscribersForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        data = form.cleaned_data
        print(data["name"])
        new_form = form.save()

    return render(request, 'mainApp/all.html', locals())


def id1(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    products_images_100 = products_images.filter(product__category__id=1)
    return render(request, 'mainApp/100.html', locals())


def id2(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    products_images_100_150 = products_images.filter(product__category__id=2)
    return render(request, 'mainApp/100_150.html', locals())

def id3(request):
    products_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    products_images_150 = products_images.filter(product__category__id=3)
    return render(request, 'mainApp/150.html', locals())

mysite/products/views.py
from django.shortcuts import render
from products.models import *


def product(request, product_id):
    product = Product.objects.get(id=product_id)


    session_key = request.session.session_key
    if not session_key:
        request.session.cycle_key()

    print(request.session.session_key)
    return render(request, 'products/product.html', locals())

mysite/mainApp/templates/products/product.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="btn-group" data-toggle="buttons">
	<div class="btn-group"><a href="/" class="btn btn-success btn-lg active">Проекты</a></div>
	<div class="btn-group"><a href="/sip" class="btn btn-success btn-lg">СИП панели</a></div>
	<div class="btn-group"><a href="/" class="btn btn-success btn-lg">Теплые крыши, перекрытия для домой из камня и дерева <span class="badge badge-secondary">New</span></a></div>
	<div class="btn-group"><a href="/" class="btn btn-success btn-lg">Отзывы</a></div>
	<div class="btn-group"><a href="/" class="btn btn-success btn-lg">Контакты</a></div>
</div>

<div class="jumbotron">
			<div class="middle" style="min-height: 50px;">
				<div class="left" style="width: 25%;min-height: 50px;float: left;">
					<div class="search"  style='width: 234px; height: 38px; margin: 6px 0px 0px 0px; background: #fff; border-radius: 4px; position: relative;'>
						<form action='/' method='post'>
								<input id='searchText' type='text' autocomplete='off' data-row='0' name='search' value='' placeholder='Поиск по сайту' style='width: 180px; height: 38px; padding: 0px 15px; background: none; border: 0px; font-size: 14px;' required />
								<input type='submit' name='search_btn' value='' style='width: 15px; height: 15px; background: url(http://villozi.com/theme/villozi/images/search.png) top center no-repeat; position: absolute; top:12px; right: 15px; cursor: pointer; border: 0px;' />
						</form>
						<div class='mainSearchRes'>
							<div class='mainSearchResBox'></div>
						</div>

					</div>
				</div>
                <div class="right" style="width:75%;min-height: 50px; float: right;">
					<div class="btn-group" data-toggle="buttons" style="width: auto; margin: 5px 137px;">
						<div class="btn-group"><a href="/100" class="btn btn-outline-success btn-sm" >до 100 м.кв.</a></div>
						<div class="btn-group"><a href="/100-150" class="btn btn-outline-success btn-sm">100 - 150 м.кв</a></div>
						<div class="btn-group"><a href="/150" class="btn btn-outline-success btn-sm">от 150 м.кв</a></div>
						<div class="btn-group"><a href="/" class="btn btn-outline-success btn-sm" style="font-size: 1.226rem;">Все проекты</a></div>
					</div>
				</div>
			</div>
	<div class="section">
		<div class="jumbotron">
			<div class="row">
                <div class="col-lg-12" style="padding: 15px;">
                    <div class="product-item">
                        <h3 style="color: #28a745">{{ product.name }}</h3>
                        <div class="row">
                            <div class="col-lg-12" style="padding-right: 115px; padding-left: 115px;">
                                <!--{% for image_item in product.productimage_set.all %}
                                    <img src="{{ image_item.image.url}}" class="img-resporsive"style="max-width: 100%; height: auto;">
                                {% endfor %}-->


								<div id="block-for-slider">
									<div id="viewport">
										<ul id="slidewrapper">

											{% for image_item in product.productimage_set.all %}
												<li class="slide"><img src="{{ image_item.image.url}}" alt="1" class="slide-img"></li>
											{% endfor %}
										</ul>

										<div id="prev-next-btns">
											<div id="prev-btn" style="background: url('{% static 'mainApp/image/left.png' %}') 40px 40px; background-size: cover;opacity: 0.7;"></div>
											<div id="next-btn" style="background: url('{% static 'mainApp/image/right.png' %}') 40px 40px; background-size: cover;opacity: 0.7;"></div>
										</div>

										<ul id="nav-btns">
											{% for image_item in product.productimage_set.all %}
												<li class="slide-nav-btn"  style="background: url('{{ image_item.image.url}}'); background-size: cover;"></li>
											{% endfor %}
										</ul>
									</div>
								</div>
                            </div>
							<div class="col-lg-5" style="padding-left: 115px;">
								<h4 style="color: #28a745; text-align:left">Параметры:</h4>
								<table class="table table-striped" style="text-align: left; width:300px" >
									<tbody>
										<tr>
										  <th scope="row">Площадь дома</th>
										  <td>{{product.area}} м.кв.</td>
										</tr>
										<tr>
											<th scope="row">Количество комнат</th>
											<td>{{product.rooms}}</td>
										</tr>
										<tr>
											<th scope="row">Тип фундамента</th>
											<td>{{product.foundation}}</td>
										</tr>
										<tr>
											<th scope="row">Высота потолков</th>
											<td>{{product.height}} м.</td>
										</tr>
										<tr>
											<th scope="row">Количество этажей</th>
											<td>{{product.floors}}</td>
										</tr>
									</tbody>
								</table>
							</div>
							<div class="col-lg-7" style="padding-right: 115px;">
								<div class="price" >
									<h5 style=" float: left; padding-top:13px;  padding-left: 190px;">Итоговая цена: </h5><h2 style="color: #28a745; text-align: right">{{product.price}}</h2>
								</div>
								<h4 style="color: #28a745; text-align:left">Дополнительные возможности:</h4>
								<div class="container_box">
									<div class="add_more">
										<input type="checkbox" name="cb" id="roof" data-price ="{{ product.price }}" data-roof="{{ product.roof_price }}" onclick="func_roof()"/>
										<label for="roof"><h4 style="float: left;">Металло черепица</h4><h5 style="color: #28a745;float: left; margin-bottom: 0; padding-top: 3px;">+{{product.roof_price}}</h5></label>
									</div>
									<div class="add_more">
										<input type="checkbox" name="cb" id="water" data-water="{{ product.water_price }}" onclick="func_water()"/>
										<label for="water"><h4 style="float: left;">Водоснабжение</h4><h5 style="color: #28a745;float: left; margin-bottom: 0; padding-top: 3px;">+{{product.water_price}}</h5></label>
									</div>
									<div class="add_more">
										<input type="checkbox" name="cb" id="front" data-front="{{ product.front_price }}" onclick="func_front()"/>
										<label for="front"><h4 style="float: left;">Отделка фасада</h4><h5 style="color: #28a745;float: left; margin-bottom: 0; padding-top: 3px;">+{{product.front_price}}</h5></label>
									</div>
								</div>
							</div>
							<p></p>
							<!--
                            <div class="col-lg-4">
                                <div class="">
                                    <h5 style="color: #28a745">
                                        Описание: {{ product.description }}
                                    </h5>
                                </div>
                                <div class="">
									<button type="submit" class="btn btn-success bth-buy"  data-price ="{{ product.price }}">{{ product.price }}</button>
                                    <p>
										Цена: data-price
                                    </p>
                                </div>
                            </div>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
			<form action="" method="post" class="form-inline text-center">{% csrf_token %}
				<div class="form-group">
					<label>Ваш email:</label>
					<input type="email" name="form.email.name" class="form-control">
				</div>
				<div class="form-group">
					<label>Ваше имя:</label>
					<input type="text" name="form.name.name" class="form-control">
				</div>
					<button type="submit" class="btn btn-primary">Отправить</button>
			</form>
</div>


{% endblock content %}